name: Go
on:
  push:
  # Also allow this workflow to be callable.
  workflow_call:
jobs:
  build:
    name: Build
    # stick with Ubuntu 20.04 LTS for older glibc compatibility
    runs-on: "ubuntu-20.04"
    steps:
    - name: Check out code
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

    - name: Set up Go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version-file: "go.mod"

    - name: Print Go Version
      run: go version

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -timeout 20m ./...

    - name: Vet
      run: go vet ./...

  gofmt:
    name: Run gofmt
    runs-on: "ubuntu-20.04"
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

    - name: Set up Go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version-file: "go.mod"

    - name: gofmt
      run: |
        if [ "$(find . -iname '*.go' | xargs gofmt -l)" ]
        then
          find . -iname '*.go' | xargs gofmt -d
          exit 1
        fi
