name: Go
on:
  push:
  # Also allow this workflow to be callable.
  workflow_call:
jobs:
  build:
    name: Build
    # stick with Ubuntu 20.04 LTS for older glibc compatibility
    runs-on: "ubuntu-20.04"
    steps:
    - name: Check out code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Go
      uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
      with:
        go-version-file: "go.mod"

    - name: Print Go Version
      run: go version

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -timeout 20m ./...

    - name: Vet
      run: go vet ./...

  gofmt:
    name: Run gofmt
    runs-on: "ubuntu-20.04"
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Go
      uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
      with:
        go-version-file: "go.mod"

    - name: gofmt
      run: |
        if [ "$(find . -iname '*.go' | xargs gofmt -l)" ]
        then
          find . -iname '*.go' | xargs gofmt -d
          exit 1
        fi
