name: Go
on:
  push:
  # Also allow this workflow to be callable.
  workflow_call:
jobs:
  build:
    name: Build
    # stick with Ubuntu 20.04 LTS for older glibc compatibility
    runs-on: "ubuntu-20.04"
    steps:
    - name: Check out code
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

    - name: Set up Go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version-file: "go.mod"

    - name: Print Go Version
      run: go version

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -timeout 20m ./...

    - name: Vet
      run: go vet ./...

  gofmt:
    name: Run gofmt
    runs-on: "ubuntu-20.04"
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

    - name: Set up Go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version-file: "go.mod"

    - name: gofmt
      run: |
        if [ "$(find . -iname '*.go' | xargs gofmt -l)" ]
        then
          find . -iname '*.go' | xargs gofmt -d
          exit 1
        fi
