name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.3.3


    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Print Go Version
      run: go version

    - name: Build
      run: go build -v -mod=readonly .

    - name: Test
      run: go test -timeout 20m -mod=readonly ./...

    - name: Vet
      run: go vet -mod=readonly ./...

  gofmt:
    name: Run gofmt
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.3.3

    - name: gofmt
      run: |
        if [ "$(find . -iname '*.go' | xargs gofmt -l)" ]
        then
          find . -iname '*.go' | xargs gofmt -d
          exit 1
        fi
