on:
  release:
    types: [published]

jobs:
  request-cli-release-refresh-at-forge:
    runs-on: ubuntu-latest
    steps:
     - name: Request CLI Release refresh @ Forge App
       run: curl -d '' https://app.stormforger.com/cli_releases/refresh --user :${FORGE_EXTERNAL_ACCESS_BASIC_AUTH_SECRET}
       env:
         FORGE_EXTERNAL_ACCESS_BASIC_AUTH_SECRET: ${{ secrets.FORGE_EXTERNAL_ACCESS_BASIC_AUTH_SECRET }}
