name: Release
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"
jobs:
  buildandtest:
    uses: ./.github/workflows/go.yml
    secrets: inherit

  build:
    # stick with Ubuntu 20.04 LTS for older glibc compatibility
    runs-on: "ubuntu-20.04"
    name: goreleaser
    needs: buildandtest
    steps:
      - name: Check out code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: "go.mod"

      - name: docker login
        run: docker login -u="${{ secrets.DOCKER_USERNAME }}" -p="${{ secrets.DOCKER_PASSWORD }}"

      - name: Release via goreleaser
        uses: goreleaser/goreleaser-action@286f3b13b1b49da4ac219696163fb8c1c93e1200 # v6.0.0
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_GORELEASER_TOKEN }}

      - name: Ping Forge to check for new Versions
        run: curl -d '' https://app.stormforger.com/cli_releases/refresh --user-agent "StormForger Github Action Pipeline" --user ":${{ secrets.FORGE_EXTERNAL_ACCESS_BASIC_AUTH_SECRET }}" --fail
