name: Release
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    name: goreleaser
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0

    - name: 'Wait for status checks'
      uses: jitterbit/await-check-suites@v1
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        timeoutSeconds: 600
        appSlugFilter: 'github-actions'

    - name: Build and push Docker images
      run: docker login -u="${{ secrets.DOCKER_USERNAME }}" -p="${{ secrets.DOCKER_PASSWORD }}"

    - name: Release via goreleaser
      uses: goreleaser/goreleaser-action@master
      with:
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_GORELEASER_TOKEN }}

    - name: Ping Forge to check for new Versions
      run: curl -d '' https://app.stormforger.com/cli_releases/refresh --user-agent "StormForger Github Action Pipeline" --user ":${{ secrets.FORGE_EXTERNAL_ACCESS_BASIC_AUTH_SECRET }}" --fail
