name: Release
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    name: goreleaser
    steps:
    - name: 'Wait for status checks'
      uses: jitterbit/await-check-suites@v1
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        timeoutSeconds: 600
        appSlugFilter: 'github-actions'

    - name: Check out code
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0

    - name: Read Go version
      id: read_versions
      run: |
        echo "::set-output name=go::$(go mod edit -json | jq -r .Go)"

    - name: Set up Go
      uses: actions/setup-go@v2.1.4
      with:
        go-version: "${{ steps.read_versions.outputs.go }}"
      id: go

    - uses: actions/cache@v2.1.6
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: docker login
      run: docker login -u="${{ secrets.DOCKER_USERNAME }}" -p="${{ secrets.DOCKER_PASSWORD }}"

    - name: Release via goreleaser
      uses: goreleaser/goreleaser-action@master
      with:
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_GORELEASER_TOKEN }}

    - name: Ping Forge to check for new Versions
      run: curl -d '' https://app.stormforger.com/cli_releases/refresh --user-agent "StormForger Github Action Pipeline" --user ":${{ secrets.FORGE_EXTERNAL_ACCESS_BASIC_AUTH_SECRET }}" --fail
