name: Release
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"
jobs:
  buildandtest:
    uses: ./.github/workflows/go.yml
    secrets: inherit

  build:
    # stick with Ubuntu 20.04 LTS for older glibc compatibility
    runs-on: "ubuntu-20.04"
    name: goreleaser
    needs: buildandtest
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version-file: "go.mod"

      - name: docker login
        run: docker login -u="${{ secrets.DOCKER_USERNAME }}" -p="${{ secrets.DOCKER_PASSWORD }}"

      - name: Release via goreleaser
        uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf # v6.1.0
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_GORELEASER_TOKEN }}

      - name: Ping Forge to check for new Versions
        run: curl -d '' https://app.stormforger.com/cli_releases/refresh --user-agent "StormForger Github Action Pipeline" --user ":${{ secrets.FORGE_EXTERNAL_ACCESS_BASIC_AUTH_SECRET }}" --fail
